#!/bin/bash

## Docker startup script with monitoring
##
## Copyright (C) 2015  Lukas Matt <lukas@zauberstuhl.de>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

source /data/monit.conf || exit 1;

echo "Hit Strg+C to exit this program!";

PID_LIST=();
for n in $(seq 0 $((${#PROCESS_LIST[*]}-1)))
do
  EXEC=${PROCESS_LIST[$n]};
  eval $EXEC & PID=$!;
  echo "[$PID]: $EXEC";
  PID_LIST+=("$PID");
done

while :;
do
  for n in $(seq 0 $((${#PID_LIST[*]}-1)))
  do
    kill -0 ${PID_LIST[$n]};
    if (( $? > 0 )); then
      PGID=$(ps -o pgid=${PID_LIST[$n]} | grep -o [0-9]*);
      echo -e "Shutting down:\n$PGID";
      kill -- -$PGID >/dev/null 2>&1;

      # normally not required but in
      # case something went wrong
      exit 1;
    fi
  done
  sleep 1;
done

exit 0;
